version: "3"

services:
  shop:
    container_name: shop
    build:
      context: .
      dockerfile: shop.Dockerfile
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: 1
      DATABASE_URL: 'postgresql://postgres:alex@db_shop:5432/db_shop'
      DATABASE_HOST: 'db'
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - webnet
#      - shop_db_net
    depends_on:
      - db_shop
    volumes:
      - ./shop:/app
    command: sh /runserver.sh

  store:
    container_name: store
    build:
      context: .
      dockerfile: store.Dockerfile
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: 1
      DATABASE_URL: 'postgresql://postgres:postgres@db_store:5432/db_store'
      DATABASE_HOST: 'db'
    ports:
      - 8001:8001
    expose:
      - 8001
    networks:
      - webnet
      - store_db_net
    depends_on:
      - db_store
    volumes:
      - ./store:/app
    command: sh /runserver.sh

  db_shop:
    container_name: db_shop
    image: postgres:12
    environment:
      POSTGRES_USER: 'alex'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'db_shop'
    expose:
      - 5432
    networks:
      - webnet
#      - shop_db_net
    volumes:
      - db_shop_vol:/var/lib/postgresql/data

  db_store:
    container_name: db_store
    image: postgres:12
    environment:
      POSTGRES_USER: 'alex'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'db_store'
    expose:
      - 5432
    networks:
      - webnet
      - store_db_net
    volumes:
      - db_store_vol:/var/lib/postgresql/data

networks:
  webnet:
  shop_db_net:
  store_db_net:

volumes:
  db_shop_vol:
  db_store_vol:
