# Generated by Django 4.1.4 on 2023-01-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_orderitem_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
    ]
